name: GigabyteDXRPGLeveling
main: com.gigabytedx.rpgleveling.Main
version: 1.0
commands:
  printskills:
    description: print out skills and info to player
  viewitems:
    description: view items in inventory
  getxp:
    description: view amount of xp you have